### ISSUE TITLE
Potential idea for running `SAMPLE_FIRST`/`SAMPLE_ONLY` for stateful tests

### ISSUE THREAD

**Issue by twentylemon** [jqwik-team/jqwik#561]
## Testing Problem

Currently the [docs](https://jqwik.net/docs/current/user-guide.html#rerunning-falsified-action-chains) read,

> Due to the fact that action chains are generated one action after the other, recreating the exact same sample of a chain is usually not possible. That’s why `AfterFailureMode.SAMPLE_ONLY` and `AfterFailureMode.SAMPLE_FIRST` will just start with the same random seed, which leads to the same sequence of chains, but not start with the last failing sample chain.

## Suggested Solution

What might be possible is to:

* have the `Random` instance also record how many random bits were requested overall (the _seek_)
* record the total number of used bits so far at try entry, before using any new bits
* store the number of bits used before the try in `.jqwik-database` along with the seed etc

Then, when re-running a sample,

* read the number of bits from the previous state; set random seed as normal
* generate random values and throw them away, for the number of bits that were used last execution
* start generating the next action chain from that randomness state

Effectively, if both seed and seek are stored, it feels like it should be possible to generate the exact same action chain without needing to generate and execute all prior actions. You pay for generating _seek_ bits on re-run, but that's still strictly less work than re-running everything.

## Discussion

Related to discussions in #303

I'm not super familiar with how `Random` works, but from reading about it just now, the seek value stored may also have to be a list of how many bits were requested. So like, `[32, 32]` instead of just `64`. That'd be less than ideal since tests generate a load of random numbers, but that list is probably very compressible, likely to be very full of `32` and `64`, so the list `[32,32]` for example could be `[(32, 2)]`; 32 appearing twice in a row.

**Comment by twentylemon** [comment]
I did some fiddling, seems like all that's needed is to store the number of times `next` is called.

https://scastie.scala-lang.org/aGzhx9HbSkmL6ETrs0Vxag

**Comment by jlink** [comment]
This might work, but would require quite some fiddling around with how jqwik currently stores its generation data.

Given that I definitely (as far as looking into the future is possible) am going to work on jqwik 2 in summer (or earlier) I don't think the effort is worth it. Jqwik 2 will have a different generation model that allows to restore generated values under most situations, especially for state-based properties. I know, because that part already works in the [proof of concept](https://github.com/jqwik-team/jqwik2-poc).

So I close this issue, because it's a core feature of jqwik 2. Hold your breath!
